# Generated by Django 4.1.4 on 2023-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('actiiv', models.BooleanField()),
            ],
        ),
    ]
