# Generated by Django 4.1.4 on 2023-05-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Std',
        ),
    ]
