# Generated by Django 4.1.4 on 2023-05-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0006_delete_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
