# Generated by Django 4.1.4 on 2023-05-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0008_loginf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginf',
        ),
    ]
