# Generated by Django 4.1.4 on 2023-06-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0011_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Trainee',
        ),
    ]
